# IF USING ATLAS (CLOUD) THE CONNECTION STRING IS AS FOLLOWS
# THIS CAN BE FOUND WHEN YOU LOGIN TO YOUR ATLAS ACCOUNT
mongo_conn="mongodb+srv://<YOUR MONGO DB USERNAME>:<YOUR MONGO DB PASSWORD>@<YOUR CONNECTION STRING>"
# IF USING LOCAL HOST THE CONNECTION STRING WILL BE AS FOLLOWS
# mongo_conn="mongodb://localhost:27017/<DATABASE_NAME>"
url="<THE LISTING URL>"
pg_username="<YOUR MONGO DB USERNAME>"
pg_password="<YOUR MONGO DB PASSWORD>"